"""included the anonymous model

Revision ID: a633fde71555
Revises: 1ffa3b04dc5c
Create Date: 2020-10-24 17:41:12.863443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a633fde71555'
down_revision = '1ffa3b04dc5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_ip', sa.Text(), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('private_key')
    )
    op.create_index(op.f('ix_anonymous_user_ip'), 'anonymous', ['user_ip'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anonymous_user_ip'), table_name='anonymous')
    op.drop_table('anonymous')
    # ### end Alembic commands ###
